services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
      image: redis:7-alpine
      container_name: redis_fsm
      ports:
        - "6379:6379"
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
volumes:
  postgres_data: